# Generated by Django 3.2.9 on 2021-12-01 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='名称')),
                ('category', models.CharField(choices=[('about', '关于我们'), ('concat', '联系我们')], max_length=20, verbose_name='类别')),
                ('content', models.TextField(verbose_name='详细内容')),
                ('status', models.CharField(choices=[('0', '不生效'), ('1', '生效')], max_length=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '相关信息',
                'verbose_name_plural': '相关信息',
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='图片名称')),
                ('pic', models.ImageField(upload_to='', verbose_name='图片地址')),
                ('intro', models.TextField(max_length=200, verbose_name='图片介绍')),
                ('status', models.CharField(choices=[('0', '不显示'), ('1', '显示')], max_length=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': 'Banner图',
                'verbose_name_plural': 'Banner图',
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='类别名称')),
                ('description', models.TimeField(null=True, verbose_name='类别介绍')),
                ('status', models.CharField(choices=[('0', '不发布'), ('1', '发布')], max_length=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '产品类别',
                'verbose_name_plural': '产品类别',
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='产品名称')),
                ('intro', models.CharField(max_length=200, verbose_name='产品介绍')),
                ('content', models.TextField(verbose_name='内容')),
                ('pic', models.ImageField(upload_to='', verbose_name='图片')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('order', models.IntegerField(default=0, verbose_name='排序,数字越大越靠前')),
                ('height', models.IntegerField(verbose_name='高度')),
                ('diameter', models.IntegerField(verbose_name='直径')),
                ('status', models.CharField(choices=[('0', '不发布'), ('1', '发布')], max_length=1, verbose_name='状态')),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.category')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['-order', 'pub_time'],
                'get_latest_by': 'id',
            },
        ),
    ]
