# Generated by Django 3.2.9 on 2021-12-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='pic',
            field=models.ImageField(upload_to='banner', verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.ImageField(upload_to='product', verbose_name='图片'),
        ),
    ]
