# Generated by Django 3.2.9 on 2021-12-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20211201_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(default='', max_length=200, verbose_name='类别接受'),
            preserve_default=False,
        ),
    ]
