# Generated by Django 3.2.9 on 2021-12-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(max_length=200, verbose_name='类别介绍'),
        ),
    ]
