# Generated by Django 3.2.9 on 2021-12-02 08:11

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='详细内容'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='intro',
            field=models.CharField(max_length=200, verbose_name='图片介绍'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='内容'),
        ),
    ]
