# Generated by Django 3.2.9 on 2021-12-03 11:27

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20211203_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=10, unique=True, verbose_name='标题')),
                ('pic', models.ImageField(upload_to='news', verbose_name='简介图片')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文')),
                ('status', models.CharField(choices=[('0', '草稿'), ('1', '发布')], max_length=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'get_latest_by': 'id',
            },
        ),
        migrations.AddField(
            model_name='about',
            name='pic',
            field=models.ImageField(default='', upload_to='about', verbose_name='简介图片'),
            preserve_default=False,
        ),
    ]
