# Generated by Django 3.2.9 on 2021-12-04 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_case'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'get_latest_by': 'id', 'ordering': ['-created_time'], 'verbose_name': '新闻', 'verbose_name_plural': '新闻'},
        ),
    ]
