# Generated by Django 3.2.9 on 2021-12-15 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_productspecs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecs',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specs', to='website.product'),
        ),
    ]
