# Generated by Django 3.2.9 on 2021-12-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_links_sitesetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': '站点设置', 'verbose_name_plural': '站点设置'},
        ),
    ]
