# Generated by Django 3.2.9 on 2021-12-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_sitesetting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecs',
            name='name',
            field=models.CharField(default='名称', max_length=36, verbose_name='产品名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='category',
            field=models.CharField(choices=[('about', '关于我们'), ('concat', '联系我们')], default='1', max_length=36, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(max_length=36, unique=True, verbose_name='图片名称'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=36, unique=True, verbose_name='类别名称'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=36, unique=True, verbose_name='产品名称'),
        ),
    ]
