# Generated by Django 3.2.9 on 2021-12-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20211215_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='productspecs',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='价格'),
        ),
    ]
