# Generated by Django 3.2.9 on 2021-12-16 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20211216_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='status',
            field=models.CharField(choices=[('0', '不发布'), ('1', '发布')], max_length=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='status',
            field=models.CharField(choices=[('0', '不发布'), ('1', '发布')], default='1', max_length=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('0', '不发布'), ('1', '发布')], max_length=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('0', '不发布'), ('1', '发布')], max_length=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.category', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='productspecs',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specs', to='website.product', verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='productspecs',
            name='status',
            field=models.BooleanField(default=True, verbose_name='状态'),
        ),
    ]
