# Generated by Django 3.2.9 on 2021-12-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20211216_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecs',
            name='status',
            field=models.CharField(choices=[('0', '不发布'), ('1', '发布')], default='1', max_length=1, verbose_name='状态'),
        ),
    ]
