# Generated by Django 3.2.9 on 2021-12-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_alter_productspecs_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'ordering': ['-order'], 'verbose_name': '友情链接', 'verbose_name_plural': '友情链接'},
        ),
        migrations.AlterField(
            model_name='links',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='analyticscode',
            field=models.CharField(default='', max_length=100, verbose_name='版权信息'),
        ),
    ]
