# Generated by Django 3.2.9 on 2021-12-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20211221_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='copyright',
            field=models.CharField(default='', max_length=100, verbose_name='版权信息'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='analyticscode',
            field=models.TextField(default='', max_length=1000, verbose_name='网站统计代码'),
        ),
    ]
